### ISSUE TITLE
Publishing your docs on Node Gem

### ISSUE THREAD

**Issue by robin-rpr** [danbev/learning-v8#17]
Hi there, 

can I ask for permission to publish your full guide to Medium? I created this Blog mainly to learn V8 myself and help others on the way. I keep a tested version tag on every story, so no worries about deprecations =)

Posted on https://node-gem.com

Would love to hear your feedback on this effort.

Thank you!

**Comment by danbev** [comment]
> can I ask for permission to publish your full guide to Medium?

Sure, that is alright :+1:
