### ISSUE TITLE
add cmake support ?

### ISSUE THREAD

**Issue by gengjiawen** [danbev/learning-v8#9]
Is it possible to do this ?

**Comment by danbev** [comment]
Sorry about the late response, I meant to reply earlier this week then totally forgot :disappointed: 

At the moment I'd like to keep it as simple as possible and stick with make. I know that things are a little messy at the moment but I'm going to clean things up as soon as I have all the existing examples/"tests" compiling and passing again.

**Comment by gengjiawen** [comment]
Update: https://github.com/bnoordhuis/v8-cmake is almost ready for all platforms.
